all:
  hosts:
    kube-master:
      ansible_host: 192.168.0.30
      ansible_user: terraform
    kube-worker-1:
      ansible_host: 192.168.0.31
      ansible_user: terraform
    kube-worker-2:
      ansible_host: 192.168.0.32
      ansible_user: terraform
    jenkins-nexus:
      ansible_host: 192.168.0.33
      ansible_user: terraform
